### ISSUE TITLE
Update dependabot ignore list

### ISSUE THREAD

**Issue by RomuloVitoi** [nearform/optic-expo#1090]
We currently ignore all `expo-*` packages: https://github.com/nearform/optic-expo/blob/master/.github/dependabot.yml#LL8C26-L8C32

`react` and `react-native` updates should be managed when updating expo with its cli and should also be ignored

`jest-expo` is similar to the `expo-*` packages and should be manually updated when upgrading the expo version (via expo doctor)

**Comment by anapaulalemos** [comment]
More info see https://github.com/nearform/optic-expo/pull/1095#discussion_r1159089306

**Comment by anapaulalemos** [comment]
After digging through the `expo-doctor` repository I found [this link](https://api.expo.dev/v2/versions/latest) where we have `sdkVersions` and inside each version there are some properties that list some of its dependencies: `relatedPackages`, `facebookReactVersion` and `facebookReactNativeVersion`.

I.e. for the expo 48.0.0:

![Screenshot 2023-04-11 at 12 13 59](https://user-images.githubusercontent.com/17121337/231208360-3f13056b-9aa0-4dfb-b938-49aea8bdfd54.png)

I believe that this can be used in some way to create the ignore list, knowing that these are the possible repositories that the `expo` wants to manage itself.

**Comment by simoneb** [comment]
nice find. why don't we implement a solution in our ci workflow which:

- checks which expo version we're running on
- grabs the packages which are related to that version
- checks if the PR is a dependabot PR and if it's bumping one of those packages
- closes the PR as not planned in that case
