### ISSUE TITLE
App sometimes crashes on iOS on opening notifications window 

### ISSUE THREAD

**Issue by AlanSl** [nearform/optic-expo#1154]
I saw this on the current App Store version of the iOS release of the app. I've not tried any development version or Expo Go, just recording it while I remember it and still have crash logs.

After getting 7 notifications, pressing the notifications window icon started causing the app to instantly crash. I'm not sure if it's related to the number of notifications or something wrong with the last one but after it started happening, the number of notifications never increased beyond 7, no notifications came through and the app crashed consistently on any tap of the notifications window.

Previously, the window would open, but for some reason I couldn't get the actual "approve?" window to show. 

I'm attaching a log [optic-2023-05-03-155021.ips.zip](https://github.com/nearform/optic-expo/files/11383852/optic-2023-05-03-155021.ips.zip) from opening the app, watching it automatically log, tapping the notifications window and it instantly crashing. The log is probably not very helpful and it's probably better to create a development build to test this.

This is on iOS 16.2 and a real iPhone SE 2nd edition. Screen recording:

https://user-images.githubusercontent.com/29628323/235958973-c8cbe186-bf57-4063-936c-78aef0d37537.mov

**Comment by AlanSl** [comment]
Screen recording:

https://user-images.githubusercontent.com/29628323/235958973-c8cbe186-bf57-4063-936c-78aef0d37537.mov

**Comment by simoneb** [comment]
@williamlines @ollyjohn is this something you've come across in your experiments?

**Comment by williamlines** [comment]
We didn't come across this specific issue, although we never had more than one notification in the notification window at a time

**Comment by tiagoheliob** [comment]
I was not able to proceed further with the investigation since I was not able to run the App on my physical device, since it's an edge case, I believe we can re-visit it later.

**Comment by simoneb** [comment]
That's ok, thanks for looking into it anyway!

**Comment by puskin94** [comment]
@simoneb I'll try to give this a shot today

**Comment by simoneb** [comment]
Closing as it's been here for a long time, and we're considering to overhaul the application anyway.
