### ISSUE TITLE
Remove eslint import plugin override for React Native imports

### ISSUE THREAD

**Issue by richiemccoll** [nearform/optic-expo#14]
The `import` plugin for ESLint doesn't find React Native components. Remove the override and comment from `.eslintrc` setting when this issue is fixed.

For more info see: https://github.com/facebook/react-native/issues/28549

**Comment by castarco** [comment]
I checked the current status of this issue, and I can't reproduce the problem anymore when I remove that override, but a different one appears.

It does not complain about its inability to find the React Native components, but about parsing problems:
```
/home/username/Code/optic-expo/src/components/Actions.tsx
  2:28  error  Parse errors in imported module 'react-native': ';' expected. (14:32)  import/namespace
```

The import line being:
```js
import { StyleSheet } from 'react-native'
```

And the one really being at fault, in `node_modules/react-native/index.js`:
```js
// Well, this one and many more with this same shape
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
```

The linter seems to struggle with this construct, adding the keyword `typeof` just before the imported object's name. I believe it's related with Flow. I'm checking how to skip that check or how to tell the linter to understand "flow" syntax.

**Comment by simoneb** [comment]
Thanks for looking into this. It's not a big issue really, we can leave this (or rephrase based on your latest findings) and wait for a solution to come to us.
