### ISSUE TITLE
Enhance OTP request flow in the app

### ISSUE THREAD

**Issue by salmanm** [nearform/optic-expo#196]
Motivation: Once I add a 2FA for npm into Optic, it can now be used for everything. Also, if I have multiple repos using the same token, I’ll get lot’s of request and will never know which repo is releasing.

So, to add more security and better experience, I propose we change the app flow as following.

- We add a secret as usual (type or scan)
- When we generate token, we allow entering some more details with the token. Details like the source (the repo this token is gonna be used for) or any other info for audit/logs.
- And do not restrict to just one token, we allow generating multiple tokens and display a list of these generated tokens somewhere (only to view and revoke/delete).
- When the request for OTP comes, we currently show a simple alert. Instead, we go to a new Screen and display the request details like the repo and/or any additional info we may have corresponding to that token and perhaps a timestamp of when the OTP for "this token" was requested in the past.

Thoughts? Feel free to post suggestions to improve the above flow.

**Comment by allforabit** [comment]
The following is a proposal of the changes to address the above items:

1. Add an extra field in the backend, `notes` similar to the notes field in github
![image](https://user-images.githubusercontent.com/537189/141820860-c1b2aa61-92e4-4abd-a3df-4a7fed30d734.png)
2. Generate token brings the user to a new page with the note text field
3. When they save they are shown a readonly screen with the note and the token (that they can copy)
4. They can click back to go to the main screen
5. The main screen will have a list of tokens and will show the start of the token note
6. Clicking on the token will bring them to the readonly token page where they can see the token
7. The OTP request lands the user on the token page with an additional message a the top about the otp request
8. The notification would have the note displayed alongside the request
9. The note for the token could be limited to a certain amount of characters to minimize storage and so it doesn't need to truncate too much for messages.

**Comment by simoneb** [comment]
Overall it makes sense with one exception. Notes are not saved in the backend. We store only the minimum amount of information that's needed for the application to work, the rest is stored in the client. Notes are associated to tokens so they make sense to be stored in the client.

**Comment by allforabit** [comment]
OK that sounds good I'll get going on it with that approach. We probably won't need any changes to the backend then.

**Comment by simoneb** [comment]
Exactly. The backend only knows the "token". If the token on the client is now associated with a note (and we can have multiple tokens for a single secret), we can simply change the client to display the note when a request for the corresponding token is received.

We need to involve a designer to design the UI

**Comment by simoneb** [comment]
@sameer-coder is the last person who worked on the backend and has a good grasp of how things work there. I do agree that this change may require changes to the server and the data model, apologies for suggesting otherwise before.
