### ISSUE TITLE
Include loading indicators when submitting to the server

### ISSUE THREAD

**Issue by allforabit** [nearform/optic-expo#258]
Currently when interacting with the server, the app briefly pauses and doesn't give an indication that something is happening in the background. Instead it should give some indication that something is happening (perhap by disabling the submit button and changing it's text or adding a spinner).

Please note that work on this should be based on the following pending PR: https://github.com/nearform/optic-expo/pull/222

**Comment by radomird** [comment]
Hi @allforabit , as far as I can see only the "Delete secret" had no loading indicator. Was there any other specific place where you know it's still missing?

**Comment by allforabit** [comment]
I actually included most loading indicators in the big PR to change the overall flow so I don't think there's actually much to add apart from the one you mentioned.

**Comment by radomird** [comment]
Great, thanks. The PR is ready for review 😃
