### ISSUE TITLE
Create secret card component

### ISSUE THREAD

**Issue by n370** [nearform/optic-expo#26]
This one seems simple in a first glance but in reality it has a fair amount of different states and special UI elements that need to be considered. The following list attempts to break down what needs to be done here.

- The most basic state is https://www.figma.com/file/weYT5rBr86ouDu3GziZGN2/Optic?node-id=28%3A5946 and it has:
  - A secret image?!
  - ~A secret name?!~ The secret issuer
  - ~A secret email address?!~ The secret account
  - A "show secret menu" icon button https://www.figma.com/file/weYT5rBr86ouDu3GziZGN2/Optic?node-id=28%3A6257 which itself has:
    - Four menu options that trigger each an specific confirmation dialog 
      - https://www.figma.com/file/weYT5rBr86ouDu3GziZGN2/Optic?node-id=28%3A6538
      - https://www.figma.com/file/weYT5rBr86ouDu3GziZGN2/Optic?node-id=28%3A6573
      - https://www.figma.com/file/weYT5rBr86ouDu3GziZGN2/Optic?node-id=28%3A6511 
  - The current OTP code for the secret (Use a placeholder for now)
  - The current OTP countdown UI component (May be challenging to implement)
  - A "show/hide secret" toggle (Maybe not necessary in this state?!)
  - A "generate token" button
- The next state is essentially the basic state:
  - Without the "generate token" button
  - With a generated token on display
- The last state is again, essentially the basic state:
  - Without the "generate token" button
  - With the "show secret" toggled on.

**Comment by simoneb** [comment]
The information contained in a OTP QR code, which can also be provided manually are:

- issuer (e.g. github.com)
- account (e.g. your github.com account name/email, can be any string)
- the secret string used to generate OTPs

When read from a QR code, these come in a standard format. See the Web implementation for reference.

**Comment by tiagoheliob** [comment]
This was already implemented https://github.com/nearform/optic-expo/pull/149
