### ISSUE TITLE
show logged user

### ISSUE THREAD

**Issue by Eomm** [nearform/optic-expo#322]
Right now it is not possible to see the login user's email.
Maybe it would be nice to show the logged email when tapping to the upper right user icon or on the settings page.

My use case: I have 2 different emails that rely on two different npm accounts.

**Comment by simoneb** [comment]
Good idea!

**Comment by simoneb** [comment]
Let's involve a designer to design this.

**Comment by mattobee** [comment]
Agree it would make sense to show the user's email address, and the email address should probably be displayed in the same place as the link to sign out.

I haven't seen the Settings screen but I'd probably suggest replacing the 'user' menu in the top right with a direct link to the that screen. That Settings screen can have the user's email address, link to sign out, and whatever other links and info we need. Does that sound sensible?

**Comment by mattobee** [comment]
@estherixz I've updated the [Figma prototype](https://www.figma.com/file/xsPf6IIM9AevLN5gZlXM4q/Optic-(Copy)?node-id=1018%3A10214) to show the proposed change. Account button in the header replaced with a Settings button, takes you to the Settings screen which now includes email address and Log Out button.

![Screenshot 2022-01-07 at 10 27 38](https://user-images.githubusercontent.com/3172945/148530626-0ebdf325-241a-4caa-a929-abc3300ec78f.png)
