### ISSUE TITLE
Improve secrets storage async methods error handling

### ISSUE THREAD

**Issue by n370** [nearform/optic-expo#36]

**Comment by radomird** [comment]
Hi @n370, did you have anything specific in mind (as the issue lacks description)?

**Comment by n370** [comment]
Hey @radomird, this part of the codebase has largely changed since the last time I worked on it. Maybe @salmanm and @sameer-coder can help you with the specifics of the implementation but my general idea here was to make sure we were properly handling whatever errors happening while saving and/or retrieving secrets from the secure secrets storage mechanism.

**Comment by simoneb** [comment]
Let's see if there's anything we should do in this regard or if the code is already good as is after the recent changes, even though I don't think anything has been done explicitly in this regard.

**Comment by radomird** [comment]
Thanks @n370 I will go through the code and will add were it is needed.

**Comment by salmanm** [comment]
I had refactored storing secrets and simplified the API there. I think it's in a good shape unless there's anything specific that we'd like to implement.

**Comment by radomird** [comment]
I've added a few unit tests in the PR, the code however looks good as it handles most of the exceptions I've tried. I did find a minor bug which is fixed in the PR as well.
