### ISSUE TITLE
Show OTP requests on application open

### ISSUE THREAD

**Issue by Eomm** [nearform/optic-expo#420]
Using the android app, if I miss the notification because I wipe out unfortunately or for whatever reason, I can not see the pending OTP requests by opening the application.

Is it possible to track all the OTP requests received and the status (waiting, approved, rejected, timeout)?

**Comment by simoneb** [comment]
It's a good idea. I have also experienced issues with notifications being lost.

**Comment by castarco** [comment]
I'm working on this issue, but I feel that it should be split into two:
- On the one hand, we want to keep track of the unacknowledged notifications, to ensure that we don't loose them.
- On the other, there's a more advanced feature: to keep a historical record of OTP requests and what happened with them.

For now I'm taking care of the first point.
