### ISSUE TITLE
Unable to switch accounts after first login

### ISSUE THREAD

**Issue by lucascontreiro** [nearform/optic-expo#596]
## Systems
Android 12

## Steps to Reproduce
1. Download Expo Go from Google Play;
2. Scan the QR code at this link with the camera and open it with Expo Go https://github.com/nearform/optic-expo/pull/590#issuecomment-1181481686;
3. Login with Google account;
4. Logout;
5. Try to login with a different account;

## Expected
- User arrives on the Google page to select which account to use;

## Actual
- User automatically goes to the home page with the account previously used on login.

**Comment by SirCQQ** [comment]
Could not reproduce it locally.

**Comment by SirCQQ** [comment]
Could not reproduce it.
