### ISSUE TITLE
Create comment on PR on after each eas update

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#682]
UPDATE 15/09/2022: we decided that the outcome of this activity is a contribution to the expo.github-action repo to make the preview comment action work with eas 

`eas update` replaces `expo publish` which posted a comment to the PR with a QR code and a link to start the app from Expo Go.

Right now the action doesn't support this feature yet. This problem is tracked in the following issue:
https://github.com/expo/expo-github-action/issues/189

**Comment by simoneb** [comment]
@confraria would it be worth contributing this feature to the expo action itself?

**Comment by confraria** [comment]
I think so. from the comments (and even some discord messages) I believe it would be useful to plenty of people.

**Comment by simoneb** [comment]
Ok cool, let's turn this activity into a contribution to that repo then

**Comment by brunopascottini** [comment]
@SirCQQ has submitted a [PR](https://github.com/expo/expo-github-action/pull/192) for this issue but it was not merged yet. I messaged the people responsible for doing. I'll keep track of that

**Comment by Mazuh** [comment]
the work is scattered on several PRs/repos (nobody has permission to actively collaborate in a more straightforward way), but here is the most updated PR: https://github.com/expo/expo-github-action/pull/200
