### ISSUE TITLE
Reconsider if building the apps on each post to master is needed

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#683]
At the moment the CI is building the apps with preview profile on each push to master.
As the production build and subsequent submission to stores never goes directly to users (there is a test phase in both app store and play store) this might not be needed.

Reconsider the utility of it after a few releases.

**Comment by confraria** [comment]
We should only trigger build on eas on opening the release branch.
And submit to the app store when release is created.

**Comment by simoneb** [comment]
> We should only trigger build on eas on opening the release branch. And submit to the app store when release is created.

are build and submit two operations that can be split?

**Comment by confraria** [comment]
yup. right now the build command is using the --auto-submit and --no-wait flag. Now I will remove both and run it on auto created release branch.
With this process we are sure that the build was successful before finishing the release and submitting to app stores.
