### ISSUE TITLE
Remove login ui

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#685]
Due to apple store guidelines it is required to implement apple login where there is another 3rd party authentication as there is currently google auth. 
Instead of adding `expo-apple-authentication` we should consider removing the explicit authentication completely:

- The secrets never leave the device, so when the user logs into another device  none of the existing secrets are restored
- When having 2 users on the same phone, the app crashes when you request a token for a user that is logged out. (Because the expo notification token is the same `ExponentPushToken[raNiw2DIurxxxxxxx]`)

# How

To avoid too much refactoring we could replace the use of `expo-auth-session` in `src/context/AuthContext.tsx#78` with a call to a new server route that would take the expo notification token, validate it, create a user if necessary and [create a custom JWT](https://firebase.google.com/docs/auth/admin/create-custom-tokens) for authentication:

```ts
const [ jwt ] = useSignInWithExpoNotificationToken(expoToken) // this method needs to be written
    
useEffect(() => {
    if (jwt) firebase.auth().signInWithCustomToken(jwt)
}, [jwt])
```

this operation can be delayed until the user creates the first token (flow for existing users will have to be considered)

# Challenges and unknowns

- ~~From what I've seen expo notification tokens are constant per app installation, but not sure if they change on upgrades (it doesn't make much sense though)~~ Acording to the [docs](https://docs.expo.dev/push-notifications/faq/#how-often-does-the--expopushtoken-) the token stays constant
- Using `expo-server-sdk` i haven't found a way to verify a token is valid without sending a notification to the user:
  * 💡 could be a way to validate the sign in: send a notification with the token and the user taps to complete the process.
 - Existing users need a migration strategy. I expect it to be relatively simple because there is already a relation between user id and expo notification token in the subscription collection

**Comment by simoneb** [comment]
How do we identify the user?

**Comment by confraria** [comment]
Using the expo notification token. The server send a notification with the token in the notification data which can be read when the user taps on it. We then use it to authenticate firebase client lib, and all the rest of the end points stay as they are.

Instead of identifying a person we identify a device.

**Comment by simoneb** [comment]
Okay but how to migrate? I mean we can't lose all the data we have now

**Comment by confraria** [comment]
There is relation with userId and expo notification token id in the subscriptions table. If there is none, it's like a new user anyway.

**Comment by simoneb** [comment]
What I mean is, if we decide to go with this, we need to keep the data users have on their devices still working once we remove the login from the app

**Comment by confraria** [comment]
data users have is always kept intact on the device. The use case we lose is multiple users per device. Which I think it's for the best.

We have edge cases with existing multiple users in the same device, but no data is lost.

**Comment by simoneb** [comment]
The server needs to change though because IIRC it's currently keying data by google user id

**Comment by confraria** [comment]
we are keying on firebase user. which mantains the same.

**Comment by simoneb** [comment]
I'm missing something. If we stop authenticating users in the app, the app will no longer send that user id to the server, so the server will have no idea who the user is, making the current data, unless migrated to a different structure, unusable. The user id in firebase is the one we get from the google login

**Comment by confraria** [comment]
Well the firebase auth is still there, but is transparent to the user. Here is some pseudo code sketch of what I'm suggesting.
```ts
const jwt = useAuthWithExpoNotificationId() // 👈 a lot is happening here

useEffect(() => {
  if (jwt) firebase.auth().signInWithCustomToken(jwt)
}, [jwt])

useEffect(() => {
  firebase.auth().onAuthStateChanged(async firebaseUser => {
    setLoading(false)
    if (!firebaseUser) return

    setUser({
      name: firebaseUser.displayName,
      email: firebaseUser.email,
      uid: firebaseUser.uid, // 👈 this is a firebase user id and what we use as reference in the db 
      idToken: await firebaseUser.getIdToken(), // 👈 this is the token we use to authenticate the requests
    })
  })
}, [])
```

```ts
function useAuthWithExpoNotificationId() {
  const [ jwt, setJwt] = useState();
  // Check if there is a saved token, if yes, use that
  // POST the expo notification token to /api/auth-expo (ExponentPushToken[raNiw2DIurxxxxxxx])
  // Receive the jwt via a notification data and setJwt(value)
  return jwt
}
```

```ts
// on the server 
async function loginOnTheServer(expoNotificationToken) {
  let uid = getUserFromExpo(expoNotificationToken) // checks if there are existing users that have this same expoNotificationToken
  if (!uid) {
    uid = createUserFromExpo(expoNotificationToken)
  }
  const jwt = await firebaseAdmin.auth().createCustomToken(uid)
  sendPushNotification({ to: expoNotificationToken, data: { jwt }}) // Only the real device
}
```

**Comment by confraria** [comment]
The problem i can't figure out with this flow is the edge case with multiple users logged in on the same device 😬 

```mermaid
graph TD
    start((start))
    start --> ntoken[Get expo_notification_token]
    ntoken --> ntoken_q{User Accepts Notification}
    ntoken_q --yes--> has_data_q{Has saved secrets?}
    ntoken_q --no--> error_token[Show error needs notifications]
    style error_token stroke:#f00,stroke-width:2px
    error_token --> e((END))
    has_data_q --yes--> has_multiple_q{Has multiple user_id?}
    has_data_q --no--> auth1[POST to /auth with expo_notification_token]
    auth1 --> notification[Receive notification with token]
    notification --> fblogin[firebase login]
    has_multiple_q --no--> auth2[POST to /auth with expo_notification_token and user_id]
    auth2 --> reply[POST reply with token]
    reply --> fblogin
    has_multiple_q --yes--> problem[/Show error? Ask User?/]
    style problem fill:red,color:white
```

**Comment by simoneb** [comment]
is there a chance that it's just simpler to set up apple auth? ;)
