### ISSUE TITLE
Get app icon to appear in expo

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-expo#693]
See 
![image](https://user-images.githubusercontent.com/20181/190423304-86662885-e564-4453-b701-a9025c8f342e.png)

There must be something to change in the app's manifest to do this

**Comment by SirCQQ** [comment]
Currently, EAS is not working correctly and will not display the icon on expo.dev or expo go on mobile this might be fixed in the future, but when building the icons are generated in builds for Android and IOS. so it will appear in the AppStore and Play Store.
