### ISSUE TITLE
add links to app stores

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#705]
![Label - app store](https://user-images.githubusercontent.com/84892/191009257-86f3b83e-b2d9-4252-ac05-98732328df2f.png)
![Label - google play](https://user-images.githubusercontent.com/84892/191009274-938f5cc3-03ac-4bd3-a923-bd2629d77a44.png)

**Comment by confraria** [comment]
Public testing link on app store
https://testflight.apple.com/join/7fjxcLqs

**Comment by Eomm** [comment]
@simoneb, there is still the link in the homepage repo that requires an update:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/11404065/194393379-2123feb0-d10b-4cf3-867a-c1fe28de7818.png">

**Comment by simoneb** [comment]
@Eomm that link works for people who are members of the org in expo. We're looking into why that doesn't work, as the app should be public and hence accessible by anybody.
