### ISSUE TITLE
Revoke apple id token on account deletion

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#720]
The apple sign in token should be revoked after account deletion. 
It's not clear from their guidelines if this is essential for app approval (account deletion is but is already implemented)
As the world 'should' and not 'must' is used.
https://developer.apple.com/support/offering-account-deletion-in-your-app/

> **My app uses Sign in with Apple to provide account creation and authentication to users. What changes are necessary to support users who delete their accounts?**
> Apps that support Sign in with Apple should use the Sign in with Apple REST API to revoke user tokens. To learn more, [review the documentation](https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens) and [design recommendations](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/accounts/).

After investigating the discussions online, I believe the best solution is to implement a solution similar to [this](https://github.com/jooyoungho/apple-token-revoke-in-firebase) on the backend running in cloud run. And calling the endpoint during the account deletion process.

**Comment by simoneb** [comment]
if more convenient we can run this in a firebase function, which is probably slightly easier to implement.
