### ISSUE TITLE
An encrypted exported list of secrets from iOS cannot be imported in android

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#759]
An [encrypted list export from iOS](https://github.com/nearform/optic-expo/files/9723790/optic-backup-20221006093937.txt) (password is A) cannot be imported in android.

**Comment by brunopascottini** [comment]
@confraria I managed to export the encrypted list and import it in android. Did I miss something? Please see the steps I did to try reproduce the issue in the following screenshots. 

<h2>From iOS Simulator -  I created two fake secrets and encrypted with a dummy "Password" for exporting.</h2>
<p>OBS: I renamed the file to the password as I ran a few attempts. It's exported by default with another pattern.</p>

<img src="https://user-images.githubusercontent.com/14056161/195605163-e441531c-0b79-4374-9f19-2268a2702741.jpeg" width="250" height="500">
<img src="https://user-images.githubusercontent.com/14056161/195609068-720904eb-18ad-4586-9425-4e899330a884.jpeg" width="250" height="500">
<img src="https://user-images.githubusercontent.com/14056161/195605288-a563234e-3ba4-4344-bffd-6fd823ae3e3d.jpeg" width="250" height="500">
<img src="https://user-images.githubusercontent.com/14056161/195605316-5ffec591-c482-4b72-8075-292034e199cf.jpeg" width="450" height="300">


<h2>On Android Studio side - Tokens were successfully imported using the "Password" when prompted. </h2>
<img src="https://user-images.githubusercontent.com/14056161/195606108-2c720f85-3032-423d-a560-082cd844af6f.jpeg" width="250" height="500">
<img src="https://user-images.githubusercontent.com/14056161/195606118-8568577a-990f-48bf-89ef-7c555be3ea82.jpeg" width="250" height="500">
<img src="https://user-images.githubusercontent.com/14056161/195610030-5637ab59-8010-4ef1-8d85-74f4b06abd16.jpeg" width="250" height="500">

**Comment by confraria** [comment]
🤦‍♂️ this is embarassing, but now it works for me too.
it must be some problem with the file I had exported before. Maybe the fact that it uses a single  character for password.
I'll close this issue then.
Sorry for the trouble.
