### ISSUE TITLE
I'd like to have: apple connect developer access for the app

### ISSUE THREAD

**Issue by brunopascottini** [nearform/optic-expo#789]
item one of [this section](https://github.com/nearform/optic-expo#running-on-a-ios-device)

**Comment by simoneb** [comment]
@confraria I'm not sure how to do this :)

**Comment by brunopascottini** [comment]
I managed to run the app in the simulator so it is not blocking me at the moment but I believe that would still be good for future contributions.

**Comment by simoneb** [comment]
The problem is I don't know what needs to be done :)

**Comment by confraria** [comment]
I'll reach out to @brunopascottini in slack

**Comment by brunopascottini** [comment]
Thank you!
