### ISSUE TITLE
Are messages delivered when the app is closed?

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-expo#838]
I'm usually running the app via expo go, so I don't know if this behavior is reproducible otherwise, and even in expo go I'm not actually sure if it reproducible consistently because I basically try to avoid it.

> Note this issue is somewhat related to #828 , although different

What I noticed over time is that if I haven't opened the expo go app, and then the optic app, the notification is now shown. It _feels_ like if the app is inactive (not sure about the right terminology here) then the notifications are not received. So, what I usually do when I need to publish something is open expo go, open the optic app, then I know that even if I close it, I will receive the push notification.

I haven't tried first of all if this is systematic (meaning if it happens all the time, since I simply avoid the problem) and second if this also happens with the native app installed from the app stores.

It would be good to figure this out. The expected outcome is that the push notifications are consistently received even if the app hasn't been recently opened on the device. Clearly, if this is a limitation of expo go we can accept it, as long as push notifications work consistently _at least_ in the native apps.

**Comment by guilhermelimak** [comment]
I can confirm this happens when using expo go if you close the app and then open expo go again to the main screen but I can't reproduce it when using the native app, so I think it wouldn't be an issue in production.

**Comment by simoneb** [comment]
Ok let's close this then.
