### ISSUE TITLE
Add support for YubiKey authentication

### ISSUE THREAD

**Issue by matijagaspar** [nearform/optic-expo#942]
YubiKey offers multiple authentication protocols and at least some of them should be fairly straight forward to implement for the optic-expo app. Investigate which protocols can be implemented in a straightforward manner and add them to optic. YubiKey can be plugged into the phone via USB (verified and works), or using NFC (needs investigation on how to implement support for it).

Potential challenges:
* YubiKey support would not require the secret to be set up on optic, but would need to somehow recognize that the request is asking for an "externaly" generated OTP and request yubikey authentication.

**Comment by eugenio-oddone** [comment]
I looked into this a little bit and there appears to be a couple libraries that should make this straightforward.

- [Here](https://www.npmjs.com/package/yub) is a package that makes Yubi verification easy. If using Firebase auth it looks like we would have to do a bit of work to add a custom 2fa step in the workflow. We would not have to store a secret with the user but would need to store the Yubi UID for the device they register to their account. Might want to have some security folks take a look at a spec before implementing.

- [Here](https://www.npmjs.com/package/react-native-nfc-manager) is a package to enable NFC scanning in React Native. It opens a prompt to scan and it worked well. Without using a lib like this, Yubi by default will try to open a link to the webpage programed in the key. Out of the box, the keys are programmed to go to the YubiKey website when they are scanned by the phone. That link includes the Yubi OTP and the page let's you verify it. I tested the lib out with a YubiKey 5 NFC and it read the OTP successfully without linking to a webpage. A caveat would be that it does not work with Expo Go.

Inserting the key into your phone via an adapter and verifying is straightforward (outside of tweaking Firebase auth) but seems like it could be a hinderance to most users. Maybe a UI/UX person could weigh in on the best approach.

As a side point, Firebase offers SMS 2fa through the platform. Not a very secure or ideal method but seems like the most straightforward 2fa implementation for the app as it is.

**Comment by matijagaspar** [comment]
@eugenio-oddone thanks for those links. Regarding storing the key, I don't think we need or should, but you set it up on NPM or basically wherever you need optic to authenticate, and than optic just forwards the otp on request

**Comment by matijagaspar** [comment]
I was able to successfully extract OTP from yubi key using nfc. I used [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) and was quite straight forward.

Basic example is: 
```javascript
        await NfcManager.requestTechnology(NfcTech.Ndef);
        // the resolved tag object will contain `ndefMessage` property
        const tag = await NfcManager.getTag();
```

However I was unable to implement the Yubikey support that would allow us to use directly with npm. This is due to the fact that npmjs uses WebAuthn. This means that you need to use the key directly on the browser and can not be proxied like the regular TOTP. In otherwords we can not use YubiKey to authenticate with npm with optic-expo or the way to possibly implement would be a very bad user experience: redirect to npm, where you authenticate with the key, and get the one time pin from npm website, than copy that pin into some field in optic to be sent to the ci.

Other findings about yubikey in general:
It supports multiple protocols, the easiest to implement and use is the OTP. You can register the public key with the end service, and than request OTP from the yubikey either with NFC, or through usb (registers as keyboard, and on gold button press will type out the OTP).

There are more advanced protocols, primarly is  FIDO U2F and extended version FIDO2. FIDO2 is the protocol used with WebAuthn. More can be found on: [fidoalliance.org/fido2](https://fidoalliance.org/fido2/) and [webauthn.io](https://webauthn.io/).

It can also act as a smart card (holding a private key certrificate) and more. Here are the [docs](https://docs.yubico.com/hardware/yubikey/yk-5/tech-manual/yk5-intro.html)

One of the issues I have encountered with yubi key is that although the documentation explains what is availible, details needed for implementation are lacking and requires a lot of digging. For example which NFC protocol is used, the returned otp is not pure but has a url structure, so needs to be additionally parsed, there was no mention of this etc....

**Comment by simoneb** [comment]
Thanks for the work on this, unfortunate that we can't use it but at least we tried!
